# Environment file for the project
name: formality-env

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - pandas
  - plotly
  - pytest
  - pytest-cov
  - matplotlib
  - jupyterlab
  - sympy
